### ISSUE TITLE
Error: File not queued

### ISSUE THREAD

**Issue by ayansengupta17** [FighterBay/YARI#1]
We get error that file not queued.
[logfile.log](https://github.com/FighterBay/YARI/files/15070683/logfile.log)

- Tested with example.sh
- Tested with streamlit app
- Tested with `curl`

**Comment by FighterBay** [comment]
Unable to reproduce even on a fresh VM.
From the logs, it looks like celery-worker isn't running/logging to disk correctly.

Can you share your docker-compose logs after running the example, please?
`sudo docker-compose logs -f -t >> yari-logs.log`

**Comment by FighterBay** [comment]
Celery's logs weren't written to disk properly because of path error in docker-compose.yaml. I have fixed it in this 6a28798f9d9759266dd658b51be93cd82e464351 commit. Please provide me logs from the disk or via docker-compose logs.

*I reckon that the error: File not queued is related to path error in the mock OCR functionality due to incorrect path being supplied. Logs from celery-worker should help.
